package on2017_11.on2017_11_22_Round_58.Anomalies;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2017_11/on2017_11_22_Round_58/Anomalies/Anomalies.task"))
			Assert.fail();
	}
}
