package on2018_05.on2018_05_02_Codeforces_Round__478__Div__2_.Problem_A________________________;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2018_05/on2018_05_02_Codeforces_Round__478__Div__2_/Problem_A________________________/Problem A - Aramejskij manuskript.json"))
			Assert.fail();
	}
}
